name: Azure Key Vault Secret Retrieval

on:
  workflow_dispatch:
    inputs:
      secretName:
        description: 'Name of the secret in Azure Key Vault'
        required: true
        default: 'mySuperSecret' # You can set a default secret name 
      runner:
          description: 'The type of runner to use, ''cirrus-ubuntu-22.04-2-core'' or ''ubuntu-latest'''
          required: true
          default: cirrus-ubuntu-22.04-2-core 

permissions:
  id-token: write
  contents: read

jobs:
  retrieve-dms-secret:
    runs-on: ${{ github.event.inputs.runner }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Azure CLI
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_DMS_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_DMS_SUBSCRIPTION_ID }}

      - name: Retrieve secret from Azure  DMS Subscription Key Vault
        run: |
          secretValue=$(az keyvault secret show --name ${{ github.event.inputs.secretName }} --vault-name "azt1kvuksdmsdevgitlock" --query value -o tsv)
          echo "SECRET_VALUE=$secretValue" >> $GITHUB_ENV

      - name: Display the secret (for demonstration only)
        run: echo "The secret is $SECRET_VALUE"

  retrieve-app-secret:
    runs-on: ${{ github.event.inputs.runner }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Azure CLI
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_APP_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_APP_SUBSCRIPTION_ID }}

      - name: Retrieve secret from Azure App Subscription Key Vault
        run: |
          secretValue=$(az keyvault secret show --name ${{ github.event.inputs.secretName }} --vault-name "azt1kvuksappdevgitlock" --query value -o tsv)
          echo "SECRET_VALUE=$secretValue" >> $GITHUB_ENV

      - name: Display the secret (for demonstration only)
        run: echo "The secret is $SECRET_VALUE"
